#!/usr/bin/python
# ipwndfu: open-source jailbreaking tool for older iOS devices
# Author: axi0mX & @shmadul

import binascii, datetime, getopt, hashlib, struct, sys, time
import dfu
import limera1n, SHAtter, steaks4uce
import subprocess
import shlex
from dfuexec import *

if __name__ == '__main__':
    opts, args = getopt.getopt(sys.argv[1:], 'pxf:')

     if len(opts) == 0:
        device = dfu.acquire_device()
        serial_number = device.serial_number
        dfu.release_device(device)
        if 'CPID:8720' in serial_number:
            steaks4uce.exploit()
        elif 'CPID:8920' in serial_number:
            limera1n.exploit()
        elif 'CPID:8922' in serial_number:
            limera1n.exploit()
        elif 'CPID:8930' in serial_number:
            SHAtter.exploit()
        else:
        	print 'Found:', serial_number
        	print 'ERROR: This device is not supported.'
        sys.exit(1)